config/routes.rb
Rails.application.routes.draw do
  resources :users, only:     [:new, :create]
  resources :entities, only:  [:new, :create, :show, :update, :edit, :destroy]
  resources :tasks, only:     [:new, :create, :update, :edit, :destroy]
  
  root 'entities#index'
  
  #=====================#
  #==== USER ROUTES ====#
  #=====================#
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
  
  #=========================#
  #==== ENTITIES ROUTES ====#
  #=========================#
  get 'entities/new', to: 'entities#new'
  post 'entities/create', to: 'entities#create'
  get 'entities/:id', to: 'entities#show'
  put 'entities/:id', to: 'entities#edit'
  post 'entities/:id', to: 'entities#update'
  delete 'entities/:id', to: 'entities#destroy' 

  #======================#
  #==== TASKS ROUTES ====#
  #======================#
  get 'tasks/new/:id', to: 'tasks#new'
  get 'tasks/create', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#edit'
  put 'tasks/:id/:status', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'

#=========================#
#==== SEARCHER ROUTES ====#
#=========================#
get '/search', to: 'searcher#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
class Entity < ApplicationRecord
  has_many :tasks, dependent: :delete_all
  belongs_to :user, foreign_key: "user_id"

  validates :name, presence: true, :uniqueness => {:scope => :user_id}
  validates :status, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :entity
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :entities
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user, :verify_entity, :init

  private

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

  def verify_entity
    @verif_entity = Entity.where(user_id: session[:user_id]).find_by(id: params[:id])
    @verif_entity.nil?
  end

  def init
    @global_entities = Entity.where(user_id: session[:user_id]).where(status: "Active")
    @entity = Entity.where(user_id: session[:user_id]).where(status: "Active")
    @entity_locked = Entity.where(user_id: session[:user_id]).where(status: "Locked")
  end
  
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authorized, :init

  def index
    @first = Entity.order(created_at: :asc).where(user_id: session[:user_id]).where(status: "Active").first()
    if !@first.nil?
      @task_by_status = {
        "not_started" => Task.where(entity_id: @first.id, status: "Not started"),
        "in_progress" => Task.where(entity_id: @first.id,status: "In progress"),
        "done" => Task.where(entity_id: @first.id, status: "Done")
      }
    end
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entities_params)
    if @entity.save
      flash[:notice] = "Entity created successfully"
      redirect_to root_path
    else
      flash[:error] = "It was not possible to create new entity"
      redirect_to root_path
    end
  end

  def show
    @single_entity = Entity.where(user_id: session[:user_id]).find(params[:id])

    if @single_entity.user_id == session[:user_id]
      @task_by_status = {
        "not_started" => Task.where(entity_id: params[:id], status: "Not started"),
        "in_progress" => Task.where(entity_id: params[:id],status: "In progress"),
        "done" => Task.where(entity_id: params[:id], status: "Done")
      }
    else
      flash[:notice] = "Error, entity consulted does not exist"
      redirect_to root_path
    end
  end

  def edit
    @single_entity = Entity.where(user_id: session[:user_id]).find(params[:id])
  end

  def update
    @single_entity = Entity.where(user_id: session[:user_id]).find(params[:id])

    params[:name].nil? == false ? @single_entity.status = "Locked" : @single_entity.update(entities_params)

    if @single_entity.save
      flash[:notice] = "Entity updated successfully"
      redirect_to root_path
    else
      flash[:error] = "Error updating entity"
      redirect_to root_path
    end
  end

  def destroy
    @single_entity = Entity.where(user_id: session[:user_id]).destroy(params[:id])
    redirect_to root_path
  end

  private

  def entities_params
    params.require(:entity).permit(:name, :status, :user_id)
  end
end

app/controllers/searcher_controller.rb
class SearcherController < ApplicationController
  def search
    @search_result = Entity.where("name LIKE ?", "%#{params[:entity_name]}%")

    if @search_result.empty?
      flash[:error] = "Entity not found"
      redirect_to root_path
      return
    end

    @search_result.each do |entity|
      if entity.user_id != session[:user_id]
        flash[:error] = "Entity not found"
        redirect_to root_path
        return
      else
        redirect_to entity_path(entity.id)
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if session[:user_id]
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else  
      render login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorized, :init
  def new
    if verify_entity
      flash[:error] = "Error creating new task"
      redirect_to root_path
    else
      @task = Task.new
    end
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save 
      flash[:notice] = "New task created successfully"
      redirect_to root_path
    else
      flash[:error] = "An error has been ocurre while creating the new task"
      redirect_to new_task_path
    end
  end

  def edit
    @task = Task.find_by(id: params[:id])
  end
  
  def update
    @task = Task.find(params[:id])

    params[:name].nil? == false ? @task.update(status: params[:status]) : @task.update(tasks_params)
    
    if @task.save
      flash[:notice] = "Task updated successfully"
      redirect_to root_path
    else
      flash[:error] = "Error updating task"
      redirect_to root_path
    end
  end

  def destroy
    @task = Task.where(entity_id: params[:id]).delete_all | Task.delete(params[:id])

    if @task > 0
      flash[:notice] = "Task deleted successfully"
      redirect_to root_path
    else
      flash[:error] = "Error deleting the task"
      redirect_to root_path
    end
  end

  private

  def tasks_params
    params.require(:task).permit(:name, :status, :endtime, :entity_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: [:show, :update, :delete]
  def new
    redirect_to root_path if session[:user_id]
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created successfully"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/edit.html.erb
<%= form_with model: @single_entity do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <%= f.text_field :status, placeholder: "Status" %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.submit %>
<% end %>

app/views/entities/index.html.erb
<%= flash[:notice] if flash[:notice] %>
<%= flash[:error] if flash[:error]%>

<% if @entity[0].nil? %>
  <div class="empty">
    <h2>There's nothig to show</h2>
    <%= link_to "Create entity", new_entity_path, class: "btn btn__action" %>
  </div>
<% else %>
  <%= render "shared/entity" %>
<% end %>

app/views/entities/new.html.erb
<div class="new_entity_form">
  <%= form_with model: @entity do |f| %>
    <%= f.text_field :name, placeholder: "Name" %>
    <%= f.text_field :status, placeholder: "Status" %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit %>
  <% end %>
</div>

app/views/entities/show.html.erb
<%= render 'shared/single_entity' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
      <%= render  "shared/navbar" %>
      <div class="main">
        <%= render  "shared/sidebar" %>
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

  </body>
</html>

app/views/shared/_entity.html.erb
<% if flash[:notice] %>
  <div id="flash-notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div id="flash-error">
    <%= flash[:error] %>
  </div>
<% end %>
<div class="entity">
  <h2><%= @entity[0].name %></h2>
  <div class="entity__header">
    <div class="entity__header--info">
      <span><%= @entity[0].name %>:</span>
      <br>
      <span id="entity_status"><%= @entity[0].status %></span>
    </div>
    <div class="entity__header--actions">

      <% if @entity[0].status == "Locked"%>
        <%= link_to "New task", "#{new_task_path}/#{@entity[0].id}", class: "btn btn__link btn__link--locked"%>
      
        <div class="filter btn btn__action btn__action--locked" role="button">Filter</div>
        <div class="sort btn btn__action btn__action--locked" role="button">Sort</div>
        <div class="show_options btn btn__action btn__action--locked" role="button">
          <span>...</span>
          <div class="options" id="options">
            <div class="lock_entity">
              <%= form_for @first do |f| %>
                <%= f.hidden_field :status, value: "Locked" %>
                <%= f.submit "Lock entity", class: "btn btn__action btn__action--locked" %>
              <% end %>
            </div>
            <div class="clear_entity">
              <%= button_to "Clear entity", task_path(@entity[0].id), method: :delete, class: "btn btn__action btn__action--locked"%>
            </div>
            <div class="delete_entity">
              <%= button_to "Delete entity", entity_path(@entity[0].id), method: :delete, class: "btn btn__action btn__action--locked" %>
            </div>
            <div class="update_entity">
              <%= link_to "Update entity", edit_entity_path(@entity[0].id), class: "btn btn__link", html: { role: "button" } %>
            </div>
          </div>
        </div>
      <% else %>
        <%= link_to "New task", "#{new_task_path}/#{@entity[0].id}", class: "btn btn__link"%>
      
        <div class="filter btn btn__action" role="button">Filter</div>
        <div class="sort btn btn__action" role="button">Sort</div>
        <div class="show_options btn btn__action" role="button">
          <span>...</span>
          <div class="options" id="options">
            <div class="lock_entity">
              <%= form_for @first do |f| %>
                <%= f.hidden_field :status, value: "Locked" %>
                <%= f.submit "Lock entity", class: "btn btn__action" %>
              <% end %>
            </div>
            <div class="clear_entity">
              <%= button_to "Clear entity", task_path(@entity[0].id), method: :delete, class: "btn btn__action"%>
            </div>
            <div class="delete_entity">
              <%= button_to "Delete entity", entity_path(@entity[0].id), method: :delete, class: "btn btn__action" %>
            </div>
            <div class="update_entity">
              <%= link_to "Update entity", edit_entity_path(@entity[0].id), class: "btn btn__link", html: { role: "button" } %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="entity__body">
    <%= render  "shared/tasks" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= form_with url: '/search', method: :get, class: 'search' do |f| %>
    <%= f.text_field :entity_name, placeholder: 'Search name' %>
    <%= f.submit "Search", disable_with: 'Searching...' %>
  <% end %>
  <%= button_to "Logout", sessions_path, method: :delete, class: "btn btn__action" %>
</div>

app/views/shared/_sidebar.erb
<div class="sidebar">  
  <div class="inbox btn btn__action" role="button">Inbox</div>
  <div class="today btn btn__action" role="button">Today</div>
  <div class="later btn btn__action" role="button">Later</div>

  <div class="entities">
    <div>
      <h3>Acive entities</h3>
      <%= link_to  "+", new_entity_path, class: "btn__link" %>
    </div>
    <div class="entities__active">
      <% if @global_entities.nil? %>
        <span>There's nothing to show</span>
      <% else %>
        <% @global_entities.each do |e| %>
          <div class="entities__item--active">
            <span>&#x25cf;</span><%= link_to e.name, entity_path(e.id), class: "btn btn__link" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div>
      <h3>Locked</h3>
    </div>
    <div class="entities__locked">
      <% if @entity_locked.nil? %>
        <span>There's nothing to show</span>
      <% else %>
        <% @entity_locked.each do |e| %>
          <div class="entities__item--locked">
            <span>&#x25cf;</span><%= link_to e.name, entity_path(e.id), class: "btn btn__link" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_single_entity.html.erb
<div class="entity">
  <h2><%= @single_entity.name %></h2>
  <div class="entity__header">
    <div class="entity__header--info">
      <span><%= @single_entity.name %></span>
      <br>
      <span><%= @single_entity.status %></span>
    </div>
    <div class="entity__header--actions">
      
      <% if @single_entity.status == "Locked"%>
        <%= link_to "New task", "#{new_task_path}/#{@single_entity.id}", class: "btn btn__link btn__link--locked"%>
        
        <div class="filter btn btn__action" role="button">Filter</div>
        <div class="sort btn btn__action" role="button">Sort</div>
        <div class="show_options btn btn__action" role="button">
          <span>...</span>
          <div class="options" id="options">
            <div class="lock_entity">
              <%= form_for @single_entity do |f| %>
                <%= f.hidden_field :status, value: "Locked" %>
                <%= f.submit "Lock entity", class: "btn btn__action btn__action--locked" %>
              <% end %>
            </div>
            <div class="clear_entity">
              <%= button_to "Clear entity", task_path(@single_entity.id), method: :delete, class: "btn btn__action btn__action--locked"%>
            </div>
            <div class="delete_entity">
              <%= button_to "Delete entity", entity_path(@single_entity.id), method: :delete, class: "btn btn__action btn__action--locked" %>
            </div>
            <div class="update_entity">
              <%= link_to "Update entity", edit_entity_path(@single_entity.id), class: "btn btn__link", html: { role: "button" } %>
            </div>
          </div>
        </div>
      <% else %>
        <%= link_to "New task", "#{new_task_path}/#{@single_entity.id}", class: "btn btn__link"%>
        
        <div class="filter btn btn__action" role="button">Filter</div>
        <div class="sort btn btn__action" role="button">Sort</div>
        <div class="show_options btn btn__action" role="button">
          <span>...</span>
          <div class="options" id="options">
            <div class="lock_entity">
              <%= form_for @single_entity do |f| %>
                <%= f.hidden_field :status, value: "Locked" %>
                <%= f.submit "Lock entity", class: "btn btn__action" %>
              <% end %>
            </div>
            <div class="clear_entity">
              <%= button_to "Clear entity", task_path(@single_entity.id), method: :delete, class: "btn btn__action"%>
            </div>
            <div class="delete_entity">
              <%= button_to "Delete entity", entity_path(@single_entity.id), method: :delete, class: "btn btn__action" %>
            </div>
            <div class="update_entity">
              <%= link_to "Update entity", edit_entity_path(@single_entity.id), class: "btn btn__link", html: { role: "button" } %>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
  <div class="entity__body">
    <%= render 'shared/tasks' %>
  </div>
</div>

app/views/shared/_tasks.html.erb
<% if flash[:notice] %>
  <div id="flash-notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div id="flash-error">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="task not_started">
  <h3>not started</h3>

  <% if !@task_by_status["not_started"].empty? %>
    <% @task_by_status["not_started"].each do |task| %>
      <div class="task__card">
        <div class="task__card--header">
          <%= task.name %>
          <span class="show_options--task">...</span>
          <div class="task__actions options_task" id="options_task">
            <%= link_to "Update task", edit_task_path(task.id), class: "btn btn__link", html: { role: "button" } %>
            <%= button_to "Delete task", task_path(task.id), method: :delete, class: "btn btn__action"%>
            <div class="task__actions--status">
              <%= form_for task do |f| %>
                <%= f.hidden_field :status, value: "In progress" %>
                <%= f.submit "In progress", class: "btn btn__action" %>
              <% end %>
              <%= form_for task do |f| %>
                <%= f.hidden_field :status, value: "Done" %>
                <%= f.submit "Done", class: "btn btn__action" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="task__card--body">
          <span class="no_description">There's no task description</span>
        </div>
        <div class="task__card--status">
          <span>Status: <%= task.status %></span>
          <span>Ends at: <%= task.endtime.strftime('%m-%d-%Y') %></span>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>There is no task</p>
  <% end %>
</div>
<div class="task in_progress">
  <h3>in progress</h3>

  <% if !@task_by_status["in_progress"].empty? %>
    <% @task_by_status["in_progress"].each do |task| %>
      <div class="task__card">
        <div class="task__card--header">
          <%= task.name %>
          <span class="show_options--task">...</span>
          <div class="task__actions options_task" id="options_task">
            <%= link_to "Update task", edit_task_path(task.id), class: "btn btn__link", html: { role: "button" } %>
            <%= button_to "Delete task", task_path(task.id), method: :delete, class: "btn btn__action"%>
            <div class="task__actions--status">
              <%= form_for task do |f| %>
                <%= f.hidden_field :status, value: "Not started" %>
                <%= f.submit "Not started", class: "btn btn__action" %>
              <% end %>
              <%= form_for task do |f| %>
                <%= f.hidden_field :status, value: "Done" %>
                <%= f.submit "Done", class: "btn btn__action" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="task__card--body">
          <span class="no_description">There's no task description</span>
        </div>
        <div class="task__card--status">
          <span>Status: <%= task.status %></span>
          <span>Ends at: <%= task.endtime.strftime('%m-%d-%Y') %></span>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>There is no task</p>
  <% end %>
</div>
<div class="task done">
  <h3>done</h3>

  <% if !@task_by_status["done"].empty? %>
    <% @task_by_status["done"].each do |task| %>
      <div class="task__card">
        <div class="task__card--header">
          <%= task.name %>
          <span class="show_options--task">...</span>
          <div class="task__actions options_task" id="options_task">
            <%= link_to "Update task", edit_task_path(task.id), class: "btn btn__link", html: { role: "button" } %>
            <%= button_to "Delete task", task_path(task.id), method: :delete, class: "btn btn__action"%>
            <div class="task__actions--status">
              <%= form_for task do |f| %>
                <%= f.hidden_field :status, value: "Not started" %>
                <%= f.submit "Not started", class: "btn btn__action" %>
              <% end %>
              <%= form_for task do |f| %>
                <%= f.hidden_field :status, value: "In progress" %>
                <%= f.submit "In progress", class: "btn btn__action" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="task__card--body">
          <span class="no_description">There's no task description</span>
        </div>
        <div class="task__card--status">
          <span>Status: <%= task.status %></span>
          <span>Ends at: <%= task.endtime.strftime('%m-%d-%Y') %></span>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>There is no task</p>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.select :status, ["Not started", "In progress", "Done"] %>
  <%= f.date_field :endtime %>
  <%= f.hidden_field :entity_id, value: @task.entity_id %>
  <%= f.submit "Update task" %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.select :status, ["Not started", "In progress", "Done"] %>
  <%= f.date_field :endtime %>
  <%= f.hidden_field :entity_id, value: params[:id] %>
  <%= f.submit "Create task" %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.text_field :username, placeholder: 'Username' %>
  <%= f.email_field :email, placeholder: 'Email' %>
  <%= f.password_field :password, placeholder: 'Password' %>
  <%= f.password_field :password_confirmation, placeholder: 'Password confirm' %>
  <%= f.submit "Create account" %>
<% end %>